kind: pipeline
type: kubernetes
name: default

steps:
- name: Test
  image: node
  commands:
  - npm ci
  - npm run build
  - npm run start

- name: Build Docker image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: nquizx/online-cv
    auto_tag: true

- name: Deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server: https://454688d5-7150-4308-8efa-eda8994be1e8.k8s.ondigitalocean.com
    kubernetes_cert:
      from_secret: KUBERNETES_CERT
    kubernetes_token:
      from_secret: KUBERNETES_TOKEN
    deployment: online-cv
    repo: nquizx/online-cv
    container: online-cv
    namespace: defaut
    tag:                 
      - linux-amd64
